apiVersion: oadp.openshift.io/v1alpha1
kind: DataProtectionApplication
metadata:
  name: velero
  namespace: openshift-adp
spec:
  configuration:
    velero:
      defaultPlugins:
        - openshift   
        - azure       
      resourceTimeout: 10m   
      backupImages: false     
    nodeAgent:
      enable: true
      uploaderType: restic
      podConfig:
        nodeSelector: {}     
  backupLocations:
    - name: velero-azure-default-1
      velero:
        provider: azure
        default: true
        objectStorage:
          bucket: velero
          prefix: velero      
        config:
          resourceGroup: <your-aro-resource-group>
          storageAccount: <your-storage-account-name>
          subscriptionId: <subscription-ID>
        credential:
          key: cloud
          name: cloud-credentials-azure
  snapshotLocations:
    - name: velero-azure-default-1
      velero:
        provider: azure
        config:
          resourceGroup: <your-aro-resource-group>
          subscriptionId: <subscription-ID>
          apiTimeout: 5m
          incremental: "true" 
